server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(3W3EUG8wODMfyB8/ur/izMMF5mmRLXtEpInHXbpQBxJvpO+9fHAjs2yuheHxtF9Zghm5yUJ0oP7Qo54j1cn5xzabZ4YYfeQPs8TVpnK1gVS0vOHSGOkb6HQ/Fh3yR0izHr/TEzN/YlMrxxrQjmEwr9kOQuGPGyKM1GiEIFJNpn+H/uaieJgYyQDWa7XTUbkM)
    username: ENC(BLouchSFSo+XA85+PRAjog==)
    password: ENC(02lwfXxHddNSss5MAeMdxDIVDRbR4IjA)

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: redis
      port: 6379
      password: ENC(h6/UhCdbaE5KrPKhUfAOo3z7MwkSywgh)

coolsms:
  api-key: ENC(DZ51nuXlLJc9MWVjZaRcGqA1CgjcdAzWr2grDlro418=)
  api-secret: ENC(JG+a++nwWff/9Gk6sZ+eUFOdX0Fj/a6pHmLGtMK2LLFltdO0SDXNbbtiWo+myHgY)
  sender-phone: ENC(lEjysN7gN2GY0RnDVA7WxNiLXzxgvawc)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  server:
    port: 9292
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/actuator

openapi:
  server-url: https://hanmo.store/api