server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Hanmo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: betlight0911

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379
      password: betlight0911

coolsms:
  api-key: ENC(DZ51nuXlLJc9MWVjZaRcGqA1CgjcdAzWr2grDlro418=)
  api-secret: ENC(JG+a++nwWff/9Gk6sZ+eUFOdX0Fj/a6pHmLGtMK2LLFltdO0SDXNbbtiWo+myHgY)
  sender-phone: ENC(lEjysN7gN2GY0RnDVA7WxNiLXzxgvawc)

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}